# Configures the "Sponsor" button shown at the top of the repository.
# https://docs.github.com/sponsors/receiving-sponsorships-through-github-sponsors/displaying-a-sponsor-button-in-your-repository
github: [kaVish2214]
